name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      # Paso 1: Check out del código
      - name: Check out code
        uses: actions/checkout@v4

      # Paso 2: Configurar Docker para SonarQube
      - name: Set up SonarQube container
        run: |
          docker network create sonarqube-network
          docker run -d --name sonarqube --network sonarqube-network -p 9000:9000 sonarqube:latest
          sleep 90 # Esperar para que SonarQube se inicie completamente

      # Paso 3: Instalar Sonar Scanner
      - name: Install Sonar Scanner
        run: |
          choco install sonarscanner -y

      # Paso 4: Analizar el código con SonarQube
      - name: Analyze code with SonarQube
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=WidgetClimaTesting \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN

      # Paso 5: Finalizar el contenedor de SonarQube
      - name: Clean up SonarQube container
        if: always()
        run: |
          docker stop sonarqube
          docker rm sonarqube
          docker network rm sonarqube-network