name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up SonarQube
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
          sleep 60 # Tiempo para que SonarQube se inicie completamente

      - name: Analyze code with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=WidgetClimaTesting \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
